# Generated by Django 2.2.1 on 2019-08-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state_msg',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
