# Generated by Django 2.2.2 on 2019-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail_image',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
