# Generated by Django 2.2.2 on 2019-07-22 01:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20190722_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profie',
            new_name='Profile',
        ),
    ]
