# Generated by Django 2.2.2 on 2019-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190722_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state_msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
