# Generated by Django 2.2.1 on 2019-08-08 00:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('setting_date_time', models.CharField(max_length=200)),
                ('pre_party', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, null=True, size=None)),
                ('acpt_party', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, null=True, size=None)),
                ('what_betting', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('per_or_one', models.CharField(blank=True, default='0', max_length=30, null=True)),
                ('per_min_money', models.CharField(blank=True, default='100', max_length=255, null=True)),
                ('setting_min', models.CharField(blank=True, default='1', max_length=50, null=True)),
                ('onetime_panalty', models.CharField(blank=True, default='0', max_length=50, null=True)),
                ('longitud', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('end', models.PositiveSmallIntegerField(default=0)),
                ('soon', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promise_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='promise.Promise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Party_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('acpt', models.PositiveSmallIntegerField(default=0)),
                ('success_or_fail', models.PositiveSmallIntegerField(default=0)),
                ('arrived_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('promise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_detail', to='promise.Promise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification_promise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_or_pro', models.CharField(max_length=1, null=True)),
                ('promise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promise_noti', to='promise.Promise')),
                ('receive_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promise_receive_user', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promise_send_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification_friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firend_receive_user', to=settings.AUTH_USER_MODEL)),
                ('send_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firend_send_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fun_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_image', models.ImageField(blank=True, null=True, upload_to='promise_fun_tmp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fun', to='promise.Party_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
