# Generated by Django 2.2.2 on 2019-06-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='setting_date_time',
            field=models.CharField(max_length=200),
        ),
    ]
