# Generated by Django 2.2.2 on 2019-06-30 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Party',
        ),
    ]
