# Generated by Django 2.2.2 on 2019-08-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='per_or_one',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
    ]
