# Generated by Django 2.2.2 on 2019-08-08 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0002_promise_per_or_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification_penalty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.CharField(blank=True, default='0', max_length=200, null=True)),
                ('Promise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_promise', to='promise.Promise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
