# Generated by Django 2.2.2 on 2019-08-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0003_notification_penalty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_penalty',
            old_name='Promise',
            new_name='promise',
        ),
    ]
