# Generated by Django 2.2.2 on 2019-06-30 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0004_auto_20190630_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='party',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, null=True, size=None),
        ),
    ]
