# Generated by Django 2.2.2 on 2019-08-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0004_auto_20190808_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_penalty',
            name='penalty',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
