# Generated by Django 2.2.2 on 2019-08-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0004_wanted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wanted',
        ),
    ]
