# Generated by Django 2.2.2 on 2019-07-20 15:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0004_auto_20190720_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notification_friend',
        ),
    ]
