# Generated by Django 2.2.2 on 2019-06-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0005_auto_20190630_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='longitud',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
