# Generated by Django 2.2.2 on 2019-08-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0005_delete_wanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_detail',
            name='penalty',
            field=models.CharField(blank=True, default='0', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='per_min_money',
            field=models.CharField(blank=True, default='100', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='what_betting',
            field=models.CharField(blank=True, default='0', max_length=30, null=True),
        ),
    ]
