# Generated by Django 2.2.2 on 2019-08-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0006_auto_20190807_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='min',
            field=models.CharField(blank=True, default='1', max_length=50, null=True),
        ),
    ]
