# Generated by Django 2.2.2 on 2019-07-30 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0006_notification_promise'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_promise',
            name='promise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promise_noti', to='promise.Promise'),
        ),
    ]
