# Generated by Django 2.2.2 on 2019-07-03 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promise', '0006_auto_20190630_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_or_fail', models.PositiveSmallIntegerField(default=0)),
                ('promise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_detail', to='promise.Promise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
