# Generated by Django 2.2.2 on 2019-07-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0007_notification_promise_promise'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_promise',
            name='com_or_pro',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
