# Generated by Django 2.2.2 on 2019-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0007_party_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='party_detail',
            name='arrived_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
