# Generated by Django 2.2.2 on 2019-07-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promise', '0008_notification_promise_com_or_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='soon',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
